services:
  - type: web
    name: souvenir_souvenir_ent_100
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: souvenir_souvenir_ent_100
          property: connectionString

databases:
  - name: souvenir_souvenir_ent_100
    plan: basic-256mb   # <-- fais correspondre au plan actuel de la DB

